- name: Enable & (Re)Start 'vnstat' systemd service, if vnstat_enabled
  systemd:
    daemon_reload: yes
    name: vnstat
    enabled: yes
    state: restarted
  when: vnstat_enabled

- name: Disable & Stop 'vnstat' systemd service, if not vnstat_enabled
  systemd:
    daemon_reload: yes
    name: vnstat
    enabled: no
    state: stopped
  when: not vnstat_enabled
