# "How do i fail a task in Ansible if the variable contains a boolean value?
# I want to perform input validation for Ansible playbooks"
# https://stackoverflow.com/questions/46664127/how-do-i-fail-a-task-in-ansible-if-the-variable-contains-a-boolean-value-i-want/46667499#46667499

# We assume 0-init/tasks/validate_vars.yml has DEFINITELY been run, so no need
# to re-check whether vars are defined here.  As Ansible vars cannot be unset:
# https://serverfault.com/questions/856729/how-to-destroy-delete-unset-a-variable-value-in-ansible

- name: Assert that "apache_install is sameas true" (boolean not string etc)
  assert:
    that: apache_install is sameas true
    fail_msg: "PLEASE SET 'apache_install: True' e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- name: Assert that "apache_enabled | type_debug == 'bool'" (boolean not string etc)
  assert:
    that: apache_enabled | type_debug == 'bool'
    fail_msg: "PLEASE GIVE VARIABLE 'apache_enabled' A PROPER (UNQUOTED) ANSIBLE BOOLEAN VALUE e.g. IN: /etc/iiab/local_vars.yml"
    quiet: yes

- debug:
    var: apache_install
- debug:
    var: apache_enabled
- debug:
    var: apache_installed


- name: Install Apache if 'apache_installed' not defined, e.g. in {{ iiab_state_file }}    # /etc/iiab/iiab_state.yml
  include_tasks: install.yml
  when: apache_installed is undefined


- name: Enable & Start-if-nec {{ apache_service }} systemd service, if apache_enabled
  systemd:
    name: "{{ apache_service }}"
    enabled: yes
    state: started    # No need to restart, as many IIAB apps do that later
  when: apache_enabled

- name: Disable & Stop {{ apache_service }} systemd service, if not apache_enabled
  systemd:
    name: "{{ apache_service }}"
    enabled: no
    state: stopped
  when: not apache_enabled


- name: Add 'apache' variable values to {{ iiab_ini_file }}
  ini_file:
    path: "{{ iiab_ini_file }}"    # /etc/iiab/iiab.ini
    section: apache
    option: "{{ item.option }}"
    value: "{{ item.value | string }}"
  with_items:
    - option: name
      value: Apache
    - option: description
      value: '"The Apache HTTP Server (''httpd'')."'
    - option: apache_install
      value: "{{ apache_install }}"
    - option: apache_enabled
      value: "{{ apache_enabled }}"
