- name: Install DokuWiki
  include_tasks: install.yml
  when: dokuwiki_install and not dokuwiki_installed is defined

- name: Enable DokuWiki
  include_tasks: enable.yml
  when: dokuwiki_install or dokuwiki_installed is defined
