export const IDENTITY = {
    0: {
        message: '',
        text: 'Hi there! This is your Identity & Access Agent. I can help you with anything related to identity management and access tools. What can I assist you with today? For example, you can ask me things like:',
        loading: false,
        time: 0,
        error: '',
        isWelcome: true,
        pre_loaded: false,
        clarify_needed: false,
        messageTime: '',
        responseTime: '0:1AM',
        show: true,

        suggestions: [
            'Get me the list of users who have access to Azure Subscriptions.',
            'Get me all SPNs with expired passwords.',
            'Show me the access activity for user John Doe.',
        ],
        response: {},
    },
    1: {
        message:
            'Get me the list of users who have access to Azure Subscriptions.',
        messageTime: '0:1AM',
        responseTime: '0:1AM',
        pre_loaded: false,
        loading: false,
        time: 7.950709104537964,
        show: false,

        error: '',
        isWelcome: false,
        clarify_needed: false,
        response: {
            headers: [
                'display_name',
                'user_principal_name',
                'subscription_name',
            ],
            result: [
                ['Anil Gaddam', 'anil@clearcompass.us', 'Azure subscription 2'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Azure subscription 2'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Azure subscription 2'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Azure subscription 2'],
                [
                    'Mohamad Choupan',
                    'mohamad.choupan@opencomply.io',
                    'Opencomply - Dev',
                ],
                ['Arta Asadi', 'arta.asadi@opencomply.io', 'Opencomply - Dev'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                [
                    'Mohamad Choupan',
                    'mohamad.choupan@opencomply.io',
                    'Opencomply - Dev',
                ],
                ['Arta Asadi', 'arta.asadi@opencomply.io', 'Opencomply - Dev'],
                [
                    'Mahan Zendedel DH',
                    'mahan.zendedel@opencomply.io',
                    'Opencomply - Dev',
                ],
                [
                    'Anil C. Gaddam',
                    'anil.gaddam@opensecurity.sh',
                    'Opencomply - Dev',
                ],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                [
                    'Anil C. Gaddam',
                    'anil.gaddam@opensecurity.sh',
                    'Opencomply - Dev',
                ],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                [
                    'Mahan Zendedel DH',
                    'mahan.zendedel@opencomply.io',
                    'Opencomply - Dev',
                ],
                ['Arta Asadi', 'arta.asadi@opencomply.io', 'Opencomply - Dev'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Opencomply - Dev'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Subscription 1'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Subscription 1'],
                ['Anil Gaddam', 'anil@clearcompass.us', 'Subscription 1'],
            ],
        },
        suggestions: [],
        text: 'Retrieve a list of users who have access to Azure Subscriptions, including their display name, user principal name, and the subscription they have access to.',
    },
    2: {
        message: 'Get me all SPNs with expired passwords.',
        messageTime: '0:1AM',
        responseTime: '0:1AM',
        pre_loaded: false,
        loading: false,
        time: 5.581084966659546,
        error: '',
        show: false,
        isWelcome: false,
        clarify_needed: false,
        response: {
            headers: ['spn'],
            result: undefined,
        },
        suggestions: [],
        text: 'Retrieve service principal names (SPNs) associated with service principals that have expired password credentials.',
    },
    3: {
        message: 'Show me the access activity for user John Doe.',
        messageTime: '0:1AM',
        responseTime: '0:2AM',
        pre_loaded: false,
        loading: false,
        time: 0,
        show: false,
        error: '',
        isWelcome: false,
        clarify_needed: false,
        response: {
            headers: ['spn'],
            result: undefined,
        },
        text: 'Retrieve the access activity for a specific user, including the user principal name, the resource accessed, and the time of access.',
    },
}
export const DEVOPS = {
    0: {
        message: '',
        text: 'Hello! This is your DevOps Agent. I can provide insights into secure code, deployment, and automation workflows. How can I assist you today? For instance, you could ask me:',
        loading: false,
        time: 0,
        error: '',
        isWelcome: true,
        pre_loaded: true,
        clarify_needed: false,
        messageTime: '',
        show: true,
        responseTime: '0:11AM',
        suggestions: [
            'What are the latest secure code scan results?',
            'Show me the deployment status for the production environment.',
            'Provide a report on automated workflow execution times.',
        ],
        response: {},
    },
    1: {
        id: 'e4c15414-2f36-4c28-a1cc-2bed0d9e2c77',
        message: 'What are the latest secure code scan results?',
        messageTime: 'Mar 24, 2025 20:35:03 UTC',
        responseTime: 'Mar 24, 2025 20:35:43 UTC',
        loading: false,
        time: 5.214944124221802,
        error: undefined,
        pre_loaded: true,
        isWelcome: false,
        clarify_needed: false,
        suggestions: [],
        show: false,

        text: 'Retrieve the latest GitHub vulnerability alerts, including the alert number, repository ID, state, severity, and CVSS score.',
        response: {
            headers: [
                'number',
                'repository_id',
                'state',
                'severity',
                'cvss_score',
            ],
            result: undefined,
        },
    },
    2: {
        id: '86b8309a-f987-493b-97b5-ef5808f77db2',
        message:
            'Show me the deployment status for the production environment.',
        messageTime: 'Mar 24, 2025 20:36:27 UTC',
        responseTime: 'Mar 24, 2025 20:37:06 UTC',
        loading: false,
        time: 3.117103338241577,
        error: undefined,
        pre_loaded: true,
        isWelcome: false,
        clarify_needed: false,
        suggestions: [],
        show: false,

        text: 'Retrieve the repository name and the last deployment time for repositories in the production environment.',
        response: {
            headers: [
                'number',
                'repository_id',
                'state',
                'severity',
                'cvss_score',
            ],
            result: undefined,
        },
    },

    3: {
        id: 'a13b8d6d-aa87-4884-9c35-de6c3f9b10d4',
        message: 'Provide a report on automated workflow execution times.',
        messageTime: 'Mar 24, 2025 20:39:45 UTC',
        responseTime: 'Mar 24, 2025 20:40:46 UTC',
        loading: false,
        time: 3.851595401763916,
        error: undefined,
        pre_loaded: true,
        isWelcome: false,
        clarify_needed: false,
        suggestions: [],
        show: false,
        text: 'Retrieve the workflow run ID, repository name, workflow name, start time, and end time for GitHub Actions workflow runs from the last month.',
        response: {
            headers: [
                'number',
                'repository_id',
                'state',
                'severity',
                'cvss_score',
            ],
            result: undefined,
        },
    },
}
