# This is a basic workflow to help you get started with Actions

name: link-check

# Controls when the workflow will run
on:
  # runs every monday at 9 am
  schedule:
    - cron: "0 9 * * 1"
    
  # Triggers the workflow on push or pull request events but only for the "master" branch
  #push:
  #  branches: [ "master" ]
  #pull_request:
  #  branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: becheran/mlc@v0.16.2
