ID: "container-syft"
Name: "Container SYFT"
Description: "Check if all container artifacts are free of vulnerabilities using SYFT"
ImageURL: "ghcr.io/opengovern/og-task-syft:v0.10.25"
Command: "/og-task-syft"
ResultType: "artifact_sbom"
WorkloadType: "deployment"
EnvVars: {}
Interval: 120
Timeout: 120 # Minutes
ScaleConfig:
  LagThreshold: "1"
  MinReplica: 0
  MaxReplica: 5