name: PR Tests

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    # we don't ignore markdkowns to run pre-commits
    paths-ignore:
      - ".github/**"

jobs:
  pr-tests-matrix:
    strategy:
      matrix:
        os: [Ubuntu]
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - os: Ubuntu
            image: ubuntu-latest
      fail-fast: false
    uses: ./.github/workflows/_test.yml
    with:
      os: ${{ matrix.os }}
      image: ${{ matrix.image }}
      python-version: ${{ matrix.python-version }}
  pr-tests-summary:
    name: PR Tests Summary
    needs: pr-tests-matrix
    runs-on: ubuntu-latest
    steps:
      - name: Confirm all PR tests passed
        run: echo "All PR Tests completed successfully"
